-- ============================================================
--  Tabela da Lobo — estrutura do banco de dados (Supabase)
--  ------------------------------------------------------------
--  Como usar: no painel do Supabase, abra "SQL Editor" →
--  "New query", cole TODO este arquivo e clique em "Run".
-- ============================================================

-- 1) Operações — cada linha pertence a um usuário (user_id)
create table if not exists public.operacoes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  data        date not null,
  valor       numeric not null default 0,
  resultado   text not null check (resultado in ('WIN', 'LOSS')),
  lucro       numeric not null default 0,
  perda       numeric not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists operacoes_user_id_idx on public.operacoes (user_id);

-- 2) Perfil / configurações de cada usuário (banca inicial e título)
create table if not exists public.perfil (
  user_id        uuid primary key references auth.users (id) on delete cascade,
  banca_inicial  numeric not null default 25,
  titulo         text not null default 'TABELA DA LOBO'
);

-- 3) Liga a Segurança por Linha (Row Level Security)
alter table public.operacoes enable row level security;
alter table public.perfil    enable row level security;

-- 4) Políticas: cada usuário só enxerga e mexe nos PRÓPRIOS dados
create policy "op_ver_proprias"     on public.operacoes for select using (auth.uid() = user_id);
create policy "op_inserir_proprias" on public.operacoes for insert with check (auth.uid() = user_id);
create policy "op_editar_proprias"  on public.operacoes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "op_excluir_proprias" on public.operacoes for delete using (auth.uid() = user_id);

create policy "perfil_ver_proprio"     on public.perfil for select using (auth.uid() = user_id);
create policy "perfil_inserir_proprio" on public.perfil for insert with check (auth.uid() = user_id);
create policy "perfil_editar_proprio"  on public.perfil for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
